/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentDashboardRouteImport } from './routes/student-dashboard'
import { Route as ResearchHubRouteImport } from './routes/research-hub'
import { Route as RefiRouteImport } from './routes/refi'
import { Route as PlatformArchitectureRouteImport } from './routes/platform-architecture'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OracleRouteImport } from './routes/oracle'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as NairobiTwinRouteImport } from './routes/nairobi-twin'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as InstitutionalEsgRouteImport } from './routes/institutional-esg'
import { Route as ImpactExplorerRouteImport } from './routes/impact-explorer'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as EcoIntelligenceRouteImport } from './routes/eco-intelligence'
import { Route as ResidentialHomesRouteImport } from './routes/residential-homes'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as IndexRouteImport } from './routes/index'

const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student-dashboard',
  path: '/student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchHubRoute = ResearchHubRouteImport.update({
  id: '/research-hub',
  path: '/research-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const RefiRoute = RefiRouteImport.update({
  id: '/refi',
  path: '/refi',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformArchitectureRoute = PlatformArchitectureRouteImport.update({
  id: '/platform-architecture',
  path: '/platform-architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OracleRoute = OracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const NairobiTwinRoute = NairobiTwinRouteImport.update({
  id: '/nairobi-twin',
  path: '/nairobi-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalEsgRoute = InstitutionalEsgRouteImport.update({
  id: '/institutional-esg',
  path: '/institutional-esg',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactExplorerRoute = ImpactExplorerRouteImport.update({
  id: '/impact-explorer',
  path: '/impact-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const EcoIntelligenceRoute = EcoIntelligenceRouteImport.update({
  id: '/eco-intelligence',
  path: '/eco-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentialHomesRoute = ResidentialHomesRouteImport.update({
  id: '/residential-homes',
  path: '/residential-homes',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/community': typeof CommunityRoute
  '/eco-intelligence': typeof EcoIntelligenceRoute
  '/residential-homes': typeof ResidentialHomesRoute
  '/governance': typeof GovernanceRoute
  '/identity': typeof IdentityRoute
  '/impact-explorer': typeof ImpactExplorerRoute
  '/institutional-esg': typeof InstitutionalEsgRoute
  '/marketplace': typeof MarketplaceRoute
  '/nairobi-twin': typeof NairobiTwinRoute
  '/observability': typeof ObservabilityRoute
  '/oracle': typeof OracleRoute
  '/orders': typeof OrdersRoute
  '/platform-architecture': typeof PlatformArchitectureRoute
  '/refi': typeof RefiRoute
  '/research-hub': typeof ResearchHubRoute
  '/student-dashboard': typeof StudentDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/community': typeof CommunityRoute
  '/eco-intelligence': typeof EcoIntelligenceRoute
  '/residential-homes': typeof ResidentialHomesRoute
  '/governance': typeof GovernanceRoute
  '/identity': typeof IdentityRoute
  '/impact-explorer': typeof ImpactExplorerRoute
  '/institutional-esg': typeof InstitutionalEsgRoute
  '/marketplace': typeof MarketplaceRoute
  '/nairobi-twin': typeof NairobiTwinRoute
  '/observability': typeof ObservabilityRoute
  '/oracle': typeof OracleRoute
  '/orders': typeof OrdersRoute
  '/platform-architecture': typeof PlatformArchitectureRoute
  '/refi': typeof RefiRoute
  '/research-hub': typeof ResearchHubRoute
  '/student-dashboard': typeof StudentDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/community': typeof CommunityRoute
  '/eco-intelligence': typeof EcoIntelligenceRoute
  '/residential-homes': typeof ResidentialHomesRoute
  '/governance': typeof GovernanceRoute
  '/identity': typeof IdentityRoute
  '/impact-explorer': typeof ImpactExplorerRoute
  '/institutional-esg': typeof InstitutionalEsgRoute
  '/marketplace': typeof MarketplaceRoute
  '/nairobi-twin': typeof NairobiTwinRoute
  '/observability': typeof ObservabilityRoute
  '/oracle': typeof OracleRoute
  '/orders': typeof OrdersRoute
  '/platform-architecture': typeof PlatformArchitectureRoute
  '/refi': typeof RefiRoute
  '/research-hub': typeof ResearchHubRoute
  '/student-dashboard': typeof StudentDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command-center'
    | '/community'
    | '/eco-intelligence'
    | '/governance'
    | '/identity'
    | '/impact-explorer'
    | '/institutional-esg'
    | '/marketplace'
    | '/nairobi-twin'
    | '/observability'
    | '/oracle'
    | '/orders'
    | '/platform-architecture'
    | '/refi'
    | '/residential-homes'
    | '/research-hub'
    | '/student-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command-center'
    | '/community'
    | '/eco-intelligence'
    | '/residential-homes'
    | '/governance'
    | '/identity'
    | '/impact-explorer'
    | '/institutional-esg'
    | '/marketplace'
    | '/nairobi-twin'
    | '/observability'
    | '/oracle'
    | '/orders'
    | '/platform-architecture'
    | '/refi'
    | '/research-hub'
    | '/student-dashboard'
  id:
    | '__root__'
    | '/'
    | '/command-center'
    | '/community'
    | '/eco-intelligence'
    | '/residential-homes'
    | '/governance'
    | '/identity'
    | '/impact-explorer'
    | '/institutional-esg'
    | '/marketplace'
    | '/nairobi-twin'
    | '/observability'
    | '/oracle'
    | '/orders'
    | '/platform-architecture'
    | '/refi'
    | '/research-hub'
    | '/student-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandCenterRoute: typeof CommandCenterRoute
  CommunityRoute: typeof CommunityRoute
  EcoIntelligenceRoute: typeof EcoIntelligenceRoute
  GovernanceRoute: typeof GovernanceRoute
  IdentityRoute: typeof IdentityRoute
  ImpactExplorerRoute: typeof ImpactExplorerRoute
  InstitutionalEsgRoute: typeof InstitutionalEsgRoute
  MarketplaceRoute: typeof MarketplaceRoute
  NairobiTwinRoute: typeof NairobiTwinRoute
  ObservabilityRoute: typeof ObservabilityRoute
  OracleRoute: typeof OracleRoute
  OrdersRoute: typeof OrdersRoute
  PlatformArchitectureRoute: typeof PlatformArchitectureRoute
  ResidentialHomesRoute: typeof ResidentialHomesRoute
  RefiRoute: typeof RefiRoute
  ResearchHubRoute: typeof ResearchHubRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-dashboard': {
      id: '/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-hub': {
      id: '/research-hub'
      path: '/research-hub'
      fullPath: '/research-hub'
      preLoaderRoute: typeof ResearchHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refi': {
      id: '/refi'
      path: '/refi'
      fullPath: '/refi'
      preLoaderRoute: typeof RefiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-architecture': {
      id: '/platform-architecture'
      path: '/platform-architecture'
      fullPath: '/platform-architecture'
      preLoaderRoute: typeof PlatformArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracle': {
      id: '/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof OracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nairobi-twin': {
      id: '/nairobi-twin'
      path: '/nairobi-twin'
      fullPath: '/nairobi-twin'
      preLoaderRoute: typeof NairobiTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional-esg': {
      id: '/institutional-esg'
      path: '/institutional-esg'
      fullPath: '/institutional-esg'
      preLoaderRoute: typeof InstitutionalEsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact-explorer': {
      id: '/impact-explorer'
      path: '/impact-explorer'
      fullPath: '/impact-explorer'
      preLoaderRoute: typeof ImpactExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eco-intelligence': {
      id: '/eco-intelligence'
      path: '/eco-intelligence'
      fullPath: '/eco-intelligence'
      preLoaderRoute: typeof EcoIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residential-homes': {
      id: '/residential-homes'
      path: '/residential-homes'
      fullPath: '/residential-homes'
      preLoaderRoute: typeof ResidentialHomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandCenterRoute: CommandCenterRoute,
  CommunityRoute: CommunityRoute,
  EcoIntelligenceRoute: EcoIntelligenceRoute,
  GovernanceRoute: GovernanceRoute,
  IdentityRoute: IdentityRoute,
  ImpactExplorerRoute: ImpactExplorerRoute,
  InstitutionalEsgRoute: InstitutionalEsgRoute,
  MarketplaceRoute: MarketplaceRoute,
  NairobiTwinRoute: NairobiTwinRoute,
  ObservabilityRoute: ObservabilityRoute,
  OracleRoute: OracleRoute,
  OrdersRoute: OrdersRoute,
  PlatformArchitectureRoute: PlatformArchitectureRoute,
  RefiRoute: RefiRoute,
  ResearchHubRoute: ResearchHubRoute,
  StudentDashboardRoute: StudentDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
