import { RoadmapItem } from "@/components/rve/roadmap-section";

// Command Center Roadmap - Global Regenerative Operations
export const COMMAND_CENTER_ROADMAP: RoadmapItem[] = [
  {
    id: "global-monitoring",
    title: "Global Ecological Monitoring Dashboard",
    description: "Build real-time monitoring system for RIUs, carbon flows, biodiversity metrics, and trading activity",
    priority: "high",
    owner: "Operations Team",
    estimatedCompletion: "Q3 2025",
    phases: [
      {
        id: "data-aggregation",
        title: "Data Aggregation Pipeline",
        description: "Build pipeline to aggregate ecological and financial data from all sources",
        status: "in-progress",
        progress: 60,
        startDate: "Mar 2025",
        endDate: "May 2025",
        deliverables: ["Data pipeline", "Real-time feeds", "Alert system"],
        dependencies: ["Data lake", "IoT network"],
      },
      {
        id: "risk-heatmaps",
        title: "Risk Heatmaps & Forecasting",
        description: "Create predictive heatmaps for ecological and financial risks",
        status: "planned",
        startDate: "May 2025",
        endDate: "Jul 2025",
        deliverables: ["Risk models", "Heatmap visualization", "Forecasting engine"],
        dependencies: ["Data aggregation", "AI decision layer"],
      },
      {
        id: "emergency-response",
        title: "Emergency Response Integration",
        description: "Connect emergency alerts to command center for crisis coordination",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["Alert integration", "Response protocols", "Crisis dashboard"],
        dependencies: ["Risk heatmaps", "Emergency layer"],
      },
    ],
  },
  {
    id: "market-surveillance",
    title: "Market Surveillance & Compliance",
    description: "Implement real-time market monitoring for fraud detection and regulatory compliance",
    priority: "critical",
    owner: "Compliance Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "transaction-monitoring",
        title: "Transaction Monitoring System",
        description: "Build real-time monitoring for all marketplace transactions",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Aug 2025",
        deliverables: ["Transaction logs", "Pattern detection", "Alert triggers"],
        dependencies: ["Marketplace engine"],
      },
      {
        id: "fraud-detection",
        title: "AI Fraud Detection",
        description: "Implement AI models for detecting fraudulent ecological claims and trades",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["Fraud models", "False positive reduction", "Investigation tools"],
        dependencies: ["Transaction monitoring", "Oracle engine"],
      },
      {
        id: "regulatory-reporting",
        title: "Regulatory Reporting Automation",
        description: "Automate ESG and climate reporting for institutional clients",
        status: "planned",
        startDate: "Oct 2025",
        endDate: "Dec 2025",
        deliverables: ["ESG reports", "API exports", "Audit trails"],
        dependencies: ["Fraud detection", "Institutional ESG"],
      },
    ],
  },
  {
    id: "planetary-command",
    title: "Planetary Command Interface",
    description: "Create unified command interface for coordinating global restoration efforts",
    priority: "medium",
    owner: "UX Team",
    estimatedCompletion: "Q2 2026",
    phases: [
      {
        id: "unified-dashboard",
        title: "Unified Command Dashboard",
        description: "Design and build unified interface for all command center functions",
        status: "planned",
        startDate: "Sep 2025",
        endDate: "Nov 2025",
        deliverables: ["Dashboard design", "Real-time updates", "Multi-screen support"],
      },
      {
        id: "crisis-coordination",
        title: "Crisis Coordination Tools",
        description: "Build tools for coordinating multi-stakeholder crisis response",
        status: "planned",
        startDate: "Nov 2025",
        endDate: "Jan 2026",
        deliverables: ["Coordination protocols", "Stakeholder management", "Communication tools"],
        dependencies: ["Unified dashboard"],
      },
      {
        id: "planetary-simulations",
        title: "Planetary-scale Simulations",
        description: "Integrate global climate and ecological simulations into command interface",
        status: "planned",
        startDate: "Jan 2026",
        endDate: "Mar 2026",
        deliverables: ["Global models", "Scenario planning", "Impact forecasting"],
        dependencies: ["Crisis coordination", "Digital twin engine"],
      },
    ],
  },
];