import { RoadmapItem } from "@/components/rve/roadmap-section";

// Community Steward Roadmap
export const COMMUNITY_ROADMAP: RoadmapItem[] = [
  {
    id: "stewardship-platform",
    title: "Community Stewardship Platform",
    description: "Build the core platform for community stewards to earn RIUs through verified ecological actions",
    priority: "critical",
    owner: "Community Team",
    estimatedCompletion: "Q3 2025",
    phases: [
      {
        id: "mobile-app",
        title: "Mobile Stewardship App",
        description: "Develop mobile app for stewards to submit evidence, track progress, and earn rewards",
        status: "in-progress",
        progress: 80,
        startDate: "Feb 2025",
        endDate: "May 2025",
        deliverables: ["Mobile app", "Evidence submission", "Progress tracking", "Reward claiming"],
        dependencies: ["User authentication"],
      },
      {
        id: "evidence-verification",
        title: "Evidence Verification System",
        description: "Build AI-powered evidence verification system for photos, GPS, and activity validation",
        status: "planned",
        startDate: "May 2025",
        endDate: "Jul 2025",
        deliverables: ["AI verification", "Photo analysis", "GPS validation", "Fraud detection"],
        dependencies: ["Mobile app"],
      },
      {
        id: "riu-earnings",
        title: "RIU Earnings & Rewards",
        description: "Implement RIU earning system with different reward tiers and bonus multipliers",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["Reward system", "Bonus multipliers", "Earning tiers", "Payment integration"],
        dependencies: ["Evidence verification"],
      },
    ],
  },
  {
    id: "gamification-features",
    title: "Gamification & Social Features",
    description: "Add gamification elements, leaderboards, and social features to increase engagement",
    priority: "high",
    owner: "Engagement Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "leaderboards",
        title: "Community Leaderboards",
        description: "Create leaderboards for individual and community achievements with real-time updates",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Aug 2025",
        deliverables: ["Individual leaderboards", "Community rankings", "Real-time updates", "Achievement badges"],
        dependencies: ["RIU earnings"],
      },
      {
        id: "missions-challenges",
        title: "Missions & Challenges",
        description: "Develop seasonal missions, challenges, and competitions tied to ecological outcomes",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["Seasonal missions", "Challenge system", "Competition framework", "Outcome tracking"],
        dependencies: ["Leaderboards"],
      },
      {
        id: "social-networking",
        title: "Social Networking Features",
        description: "Build social features for stewards to connect, share stories, and collaborate",
        status: "planned",
        startDate: "Oct 2025",
        endDate: "Dec 2025",
        deliverables: ["Social profiles", "Story sharing", "Collaboration tools", "Community forums"],
        dependencies: ["Missions challenges"],
      },
    ],
  },
  {
    id: "mpesa-integration",
    title: "M-Pesa Payment Integration",
    description: "Integrate M-Pesa for seamless cash-out of RIU earnings and microgrant disbursements",
    priority: "medium",
    owner: "Payments Team",
    estimatedCompletion: "Q1 2026",
    phases: [
      {
        id: "mpesa-api",
        title: "M-Pesa API Integration",
        description: "Integrate with M-Pesa APIs for B2C payouts and STK push payments",
        status: "in-progress",
        progress: 60,
        startDate: "Apr 2025",
        endDate: "Jun 2025",
        deliverables: ["B2C integration", "STK integration", "API security", "Error handling"],
        dependencies: ["RIU earnings"],
      },
      {
        id: "cashback-system",
        title: "Climate Cashback System",
        description: "Implement climate cashback system for verified sustainable behaviors",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Aug 2025",
        deliverables: ["Cashback rules", "Behavior tracking", "Automated payouts", "Reporting"],
        dependencies: ["M-Pesa API"],
      },
      {
        id: "microgrants",
        title: "Microgrant Distribution",
        description: "Build microgrant system for community projects and restoration initiatives",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["Grant application", "Project tracking", "Fund distribution", "Impact measurement"],
        dependencies: ["Cashback system"],
      },
    ],
  },
];