import { RoadmapItem } from "@/components/rve/roadmap-section";

// Eco Intelligence Roadmap - AI Brain Development
export const ECO_INTELLIGENCE_ROADMAP: RoadmapItem[] = [
  {
    id: "biosphere-modeling",
    title: "Biosphere Reasoning Graph Ensemble",
    description: "Build comprehensive AI models for ecological forecasting, restoration recommendations, and climate risk assessment",
    priority: "critical",
    owner: "AI Research Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "model-architecture",
        title: "Ensemble Model Architecture",
        description: "Design multi-model ensemble architecture for ecological intelligence",
        status: "in-progress",
        progress: 70,
        startDate: "Jan 2025",
        endDate: "Apr 2025",
        deliverables: ["Model architecture", "Training pipeline", "Ensemble logic"],
        dependencies: ["Data lake infrastructure"],
      },
      {
        id: "climate-forecasting",
        title: "Climate Impact Forecasting",
        description: "Build predictive models for climate change impacts on ecosystems",
        status: "planned",
        startDate: "Apr 2025",
        endDate: "Jun 2025",
        deliverables: ["Climate models", "Impact predictions", "Uncertainty quantification"],
        dependencies: ["Model architecture"],
      },
      {
        id: "restoration-optimization",
        title: "Restoration Opportunity Mapping",
        description: "AI-driven identification and prioritization of restoration opportunities",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Aug 2025",
        deliverables: ["Opportunity mapping", "Cost-benefit analysis", "Priority scoring"],
        dependencies: ["Climate forecasting"],
      },
    ],
  },
  {
    id: "species-recovery",
    title: "Species Recovery Intelligence",
    description: "AI systems for endangered species monitoring, habitat restoration, and biodiversity enhancement",
    priority: "high",
    owner: "Conservation AI Team",
    estimatedCompletion: "Q1 2026",
    phases: [
      {
        id: "species-monitoring",
        title: "Automated Species Monitoring",
        description: "Computer vision and acoustic monitoring for wildlife populations",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["Species detection", "Population tracking", "Habitat analysis"],
        dependencies: ["IoT sensor network"],
      },
      {
        id: "habitat-modeling",
        title: "Habitat Suitability Modeling",
        description: "Predict optimal habitats for species recovery and restoration planning",
        status: "planned",
        startDate: "Sep 2025",
        endDate: "Nov 2025",
        deliverables: ["Habitat models", "Connectivity analysis", "Restoration planning"],
        dependencies: ["Species monitoring", "Geospatial system"],
      },
      {
        id: "intervention-recommendations",
        title: "AI Intervention Recommendations",
        description: "Generate actionable recommendations for species recovery interventions",
        status: "planned",
        startDate: "Nov 2025",
        endDate: "Jan 2026",
        deliverables: ["Intervention models", "Success prediction", "Resource optimization"],
        dependencies: ["Habitat modeling"],
      },
    ],
  },
  {
    id: "real-time-alerts",
    title: "Real-time Ecological Alert System",
    description: "Build comprehensive alert system for ecological threats, degradation events, and intervention opportunities",
    priority: "high",
    owner: "Monitoring Team",
    estimatedCompletion: "Q3 2025",
    phases: [
      {
        id: "threat-detection",
        title: "Threat Detection Engine",
        description: "AI-powered detection of ecological threats and degradation events",
        status: "in-progress",
        progress: 50,
        startDate: "Mar 2025",
        endDate: "May 2025",
        deliverables: ["Threat models", "Anomaly detection", "Alert generation"],
        dependencies: ["IoT network", "Satellite integration"],
      },
      {
        id: "alert-prioritization",
        title: "Alert Prioritization & Routing",
        description: "Smart prioritization and routing of alerts to appropriate stakeholders",
        status: "planned",
        startDate: "May 2025",
        endDate: "Jul 2025",
        deliverables: ["Priority scoring", "Stakeholder mapping", "Alert routing"],
        dependencies: ["Threat detection"],
      },
      {
        id: "intervention-coordination",
        title: "Intervention Coordination Platform",
        description: "Platform for coordinating rapid response to ecological alerts",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["Response coordination", "Resource allocation", "Impact tracking"],
        dependencies: ["Alert prioritization"],
      },
    ],
  },
];