import { RoadmapItem } from "@/components/rve/roadmap-section";

// Governance & DAO Roadmap
export const GOVERNANCE_ROADMAP: RoadmapItem[] = [
  {
    id: "proposal-system",
    title: "Proposal & Voting System",
    description: "Build comprehensive proposal creation, discussion, and quadratic voting system",
    priority: "critical",
    owner: "Governance Team",
    estimatedCompletion: "Q3 2025",
    phases: [
      {
        id: "proposal-creation",
        title: "Proposal Creation Platform",
        description: "Build user-friendly proposal creation interface with templates and validation",
        status: "in-progress",
        progress: 70,
        startDate: "Feb 2025",
        endDate: "Apr 2025",
        deliverables: ["Proposal templates", "Validation system", "Rich text editor", "Proposal preview"],
        dependencies: ["User authentication"],
      },
      {
        id: "quadratic-voting",
        title: "Quadratic Voting Implementation",
        description: "Implement quadratic voting mechanism with credit allocation and vote counting",
        status: "planned",
        startDate: "Apr 2025",
        endDate: "Jun 2025",
        deliverables: ["Voting algorithm", "Credit system", "Vote counting", "Result calculation"],
        dependencies: ["Proposal creation"],
      },
      {
        id: "discussion-forum",
        title: "Proposal Discussion Forum",
        description: "Build threaded discussion system for proposal deliberation and feedback",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Aug 2025",
        deliverables: ["Discussion threads", "Comment system", "Moderation tools", "Notification system"],
        dependencies: ["Proposal creation"],
      },
    ],
  },
  {
    id: "treasury-management",
    title: "Treasury Management System",
    description: "Develop comprehensive treasury management with multi-asset support and automated payouts",
    priority: "high",
    owner: "Treasury Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "multi-asset-treasury",
        title: "Multi-Asset Treasury",
        description: "Implement treasury system supporting RIUs, KES, and other ecological assets",
        status: "planned",
        startDate: "May 2025",
        endDate: "Jul 2025",
        deliverables: ["Asset management", "Balance tracking", "Transaction history", "Asset conversion"],
        dependencies: ["Database setup"],
      },
      {
        id: "automated-payouts",
        title: "Automated Payout System",
        description: "Build automated payout system for mission rewards, grants, and ecosystem funding",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["Payout automation", "Grant distribution", "Reward system", "Audit trails"],
        dependencies: ["Multi-asset treasury"],
      },
      {
        id: "budget-planning",
        title: "Budget Planning & Forecasting",
        description: "Create budget planning tools with forecasting and scenario modeling",
        status: "planned",
        startDate: "Sep 2025",
        endDate: "Nov 2025",
        deliverables: ["Budget planning", "Forecasting tools", "Scenario modeling", "Reporting dashboard"],
        dependencies: ["Automated payouts"],
      },
    ],
  },
  {
    id: "participation-network",
    title: "Participation & Reputation Network",
    description: "Build geographic participation mapping and reputation-weighted governance system",
    priority: "medium",
    owner: "Community Team",
    estimatedCompletion: "Q1 2026",
    phases: [
      {
        id: "geographic-mapping",
        title: "Geographic Participation Mapping",
        description: "Create interactive maps showing governance participation by geographic region",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["Geographic maps", "Participation data", "Regional analytics", "Visualization tools"],
        dependencies: ["User profiles"],
      },
      {
        id: "reputation-weighted-voting",
        title: "Reputation-Weighted Voting",
        description: "Implement reputation-weighted voting system based on ecological impact and participation",
        status: "planned",
        startDate: "Oct 2025",
        endDate: "Dec 2025",
        deliverables: ["Reputation weights", "Voting power calculation", "Participation tracking", "Fairness algorithms"],
        dependencies: ["RID scoring system"],
      },
      {
        id: "delegation-system",
        title: "Vote Delegation System",
        description: "Build vote delegation system allowing users to delegate voting power to trusted representatives",
        status: "planned",
        startDate: "Dec 2025",
        endDate: "Feb 2026",
        deliverables: ["Delegation interface", "Delegate management", "Trust networks", "Delegation tracking"],
        dependencies: ["Reputation-weighted voting"],
      },
    ],
  },
];