import { RoadmapItem } from "@/components/rve/roadmap-section";

// Identity & RID Scoring Roadmap
export const IDENTITY_ROADMAP: RoadmapItem[] = [
  {
    id: "user-identity-system",
    title: "User Identity & Profile System",
    description: "Build comprehensive user identity management with profiles, verification, and reputation tracking",
    priority: "critical",
    owner: "Identity Team",
    estimatedCompletion: "Q2 2025",
    phases: [
      {
        id: "user-profiles",
        title: "User Profile Management",
        description: "Create user profile system with personal information, preferences, and ecological interests",
        status: "completed",
        progress: 100,
        startDate: "Jan 2025",
        endDate: "Feb 2025",
        deliverables: ["Profile creation", "Profile editing", "Avatar upload", "Preference settings"],
        dependencies: ["Database setup"],
      },
      {
        id: "identity-verification",
        title: "Multi-Channel Identity Verification",
        description: "Implement phone, email, document, and community-based identity verification",
        status: "in-progress",
        progress: 75,
        startDate: "Feb 2025",
        endDate: "Apr 2025",
        deliverables: ["Phone verification", "Email verification", "Document verification", "Community attestation"],
        dependencies: ["User profiles"],
      },
      {
        id: "profile-api",
        title: "Profile Management API",
        description: "Build RESTful API for profile CRUD operations and data retrieval",
        status: "completed",
        progress: 100,
        startDate: "Mar 2025",
        endDate: "Mar 2025",
        deliverables: ["Profile API endpoints", "Data validation", "Error handling", "API documentation"],
        dependencies: ["User profiles"],
      },
    ],
  },
  {
    id: "rid-scoring-system",
    title: "RID Scoring & Reputation Engine",
    description: "Develop the Regenerative Impact Dashboard scoring system with multi-domain reputation tracking",
    priority: "high",
    owner: "Scoring Team",
    estimatedCompletion: "Q3 2025",
    phases: [
      {
        id: "rid-algorithm",
        title: "RID Scoring Algorithm",
        description: "Design and implement the core RID scoring algorithm with weighted reputation domains",
        status: "in-progress",
        progress: 60,
        startDate: "Mar 2025",
        endDate: "May 2025",
        deliverables: ["Scoring algorithm", "Weight calculations", "Domain definitions", "Score normalization"],
        dependencies: ["User profiles"],
      },
      {
        id: "reputation-domains",
        title: "Reputation Domain System",
        description: "Implement reputation tracking across Steward, Oracle, Research, Civic, and Builder domains",
        status: "planned",
        startDate: "May 2025",
        endDate: "Jul 2025",
        deliverables: ["Domain definitions", "Reputation tracking", "Domain scoring", "Progress visualization"],
        dependencies: ["RID algorithm"],
      },
      {
        id: "achievement-system",
        title: "Achievement & Badge System",
        description: "Create achievement system with badges, certifications, and milestone tracking",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["Achievement definitions", "Badge system", "Certification tracking", "Milestone rewards"],
        dependencies: ["Reputation domains"],
      },
    ],
  },
  {
    id: "trust-network",
    title: "Trust Network & Social Verification",
    description: "Build social verification network with peer endorsements and community trust signals",
    priority: "medium",
    owner: "Social Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "peer-endorsements",
        title: "Peer Endorsement System",
        description: "Implement peer-to-peer endorsement system for reputation building",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Aug 2025",
        deliverables: ["Endorsement requests", "Endorsement validation", "Trust scoring", "Endorsement history"],
        dependencies: ["Reputation domains"],
      },
      {
        id: "community-verification",
        title: "Community Verification Network",
        description: "Build community-based verification system with local validators and attestors",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["Community validators", "Local attestation", "Verification network", "Trust propagation"],
        dependencies: ["Peer endorsements"],
      },
      {
        id: "trust-metrics",
        title: "Trust Metrics Dashboard",
        description: "Create comprehensive trust metrics dashboard showing network health and verification stats",
        status: "planned",
        startDate: "Oct 2025",
        endDate: "Dec 2025",
        deliverables: ["Trust dashboard", "Network metrics", "Verification stats", "Trust visualization"],
        dependencies: ["Community verification"],
      },
    ],
  },
];