import { RoadmapItem } from "@/components/rve/roadmap-section";

// Impact Explorer Roadmap - Public Transparency Portal
export const IMPACT_EXPLORER_ROADMAP: RoadmapItem[] = [
  {
    id: "open-data-portal",
    title: "Open Ecological Data Portal",
    description: "Build comprehensive public portal for restoration maps, datasets, and research access",
    priority: "high",
    owner: "Data Team",
    estimatedCompletion: "Q3 2025",
    phases: [
      {
        id: "data-catalog",
        title: "Open Data Catalog",
        description: "Create searchable catalog of ecological datasets and research materials",
        status: "in-progress",
        progress: 40,
        startDate: "Feb 2025",
        endDate: "Apr 2025",
        deliverables: ["Data catalog", "Search interface", "API access"],
        dependencies: ["Data lake"],
      },
      {
        id: "restoration-maps",
        title: "Interactive Restoration Maps",
        description: "Build public maps showing restoration projects and ecological changes",
        status: "planned",
        startDate: "Apr 2025",
        endDate: "Jun 2025",
        deliverables: ["Interactive maps", "Project overlays", "Time series"],
        dependencies: ["Geospatial system", "Data catalog"],
      },
      {
        id: "researcher-tools",
        title: "Researcher Collaboration Tools",
        description: "Tools for researchers to access data, collaborate, and publish findings",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Aug 2025",
        deliverables: ["Collaboration platform", "Data analysis tools", "Publication workflow"],
        dependencies: ["Restoration maps"],
      },
    ],
  },
  {
    id: "storytelling-platform",
    title: "Community Storytelling Platform",
    description: "Platform for communities to share restoration stories, photos, and impact narratives",
    priority: "medium",
    owner: "Community Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "story-collection",
        title: "Story Collection System",
        description: "Mobile-friendly system for collecting community stories and media",
        status: "planned",
        startDate: "May 2025",
        endDate: "Jul 2025",
        deliverables: ["Story submission", "Media upload", "Community profiles"],
        dependencies: ["Mobile app"],
      },
      {
        id: "impact-narratives",
        title: "Impact Narrative Platform",
        description: "Platform for creating compelling narratives around restoration impact",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["Story curation", "Multimedia presentations", "Impact metrics"],
        dependencies: ["Story collection"],
      },
      {
        id: "global-showcase",
        title: "Global Restoration Showcase",
        description: "Showcase successful restoration projects and community stories worldwide",
        status: "planned",
        startDate: "Sep 2025",
        endDate: "Nov 2025",
        deliverables: ["Project showcase", "Success stories", "Global map"],
        dependencies: ["Impact narratives"],
      },
    ],
  },
  {
    id: "media-integration",
    title: "Media & Press Integration",
    description: "Tools and feeds for journalists, media outlets, and public communication",
    priority: "medium",
    owner: "Communications Team",
    estimatedCompletion: "Q2 2026",
    phases: [
      {
        id: "press-feeds",
        title: "Real-time Press Feeds",
        description: "RSS feeds and APIs for media outlets to access restoration news and data",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["RSS feeds", "Press APIs", "News aggregation"],
        dependencies: ["Data portal"],
      },
      {
        id: "visualization-tools",
        title: "Advanced Visualization Tools",
        description: "Tools for creating compelling visualizations of ecological data and trends",
        status: "planned",
        startDate: "Oct 2025",
        endDate: "Dec 2025",
        deliverables: ["Chart builder", "Infographics", "Interactive dashboards"],
        dependencies: ["Press feeds"],
      },
      {
        id: "media-partnerships",
        title: "Media Partnership Platform",
        description: "Platform for collaborating with media partners on ecological storytelling",
        status: "planned",
        startDate: "Dec 2025",
        endDate: "Feb 2026",
        deliverables: ["Partnership tools", "Content collaboration", "Distribution network"],
        dependencies: ["Visualization tools"],
      },
    ],
  },
];