import { RoadmapItem } from "@/components/rve/roadmap-section";

// Institutional ESG Roadmap
export const INSTITUTIONAL_ESG_ROADMAP: RoadmapItem[] = [
  {
    id: "esg-reporting-platform",
    title: "ESG Reporting & Analytics Platform",
    description: "Build comprehensive ESG reporting platform with portfolio analytics and regulatory compliance",
    priority: "critical",
    owner: "ESG Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "portfolio-analytics",
        title: "Portfolio ESG Analytics",
        description: "Develop portfolio-level ESG analytics with climate, nature, and social metrics",
        status: "in-progress",
        progress: 75,
        startDate: "Feb 2025",
        endDate: "May 2025",
        deliverables: ["Portfolio dashboard", "ESG scoring", "Benchmarking", "Trend analysis"],
        dependencies: ["Data integration"],
      },
      {
        id: "regulatory-reporting",
        title: "Regulatory Reporting System",
        description: "Build automated regulatory reporting for SFDR, CSRD, and other ESG frameworks",
        status: "planned",
        startDate: "May 2025",
        endDate: "Jul 2025",
        deliverables: ["SFDR templates", "CSRD compliance", "Automated reporting", "Audit trails"],
        dependencies: ["Portfolio analytics"],
      },
      {
        id: "api-integration",
        title: "API & Data Integration",
        description: "Create APIs for real-time ESG data integration and third-party system connectivity",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["REST APIs", "Webhook system", "Data export", "Integration docs"],
        dependencies: ["Regulatory reporting"],
      },
    ],
  },
  {
    id: "impact-measurement",
    title: "Impact Measurement & Attribution",
    description: "Develop advanced impact measurement with attribution modeling and outcome verification",
    priority: "high",
    owner: "Impact Team",
    estimatedCompletion: "Q1 2026",
    phases: [
      {
        id: "sdg-alignment",
        title: "SDG Alignment Framework",
        description: "Build SDG alignment framework with automated mapping and contribution measurement",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Aug 2025",
        deliverables: ["SDG mapping", "Contribution metrics", "Target tracking", "Progress reporting"],
        dependencies: ["Portfolio analytics"],
      },
      {
        id: "impact-attribution",
        title: "Impact Attribution Modeling",
        description: "Develop attribution models for measuring portfolio impact on environmental and social outcomes",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["Attribution models", "Counterfactual analysis", "Impact pathways", "Validation methods"],
        dependencies: ["SDG alignment"],
      },
      {
        id: "outcome-verification",
        title: "Outcome Verification System",
        description: "Implement third-party verification and assurance for ESG claims and impact reports",
        status: "planned",
        startDate: "Oct 2025",
        endDate: "Dec 2025",
        deliverables: ["Verification protocols", "Assurance framework", "Audit processes", "Certification"],
        dependencies: ["Impact attribution"],
      },
    ],
  },
  {
    id: "enterprise-integration",
    title: "Enterprise Integration & Governance",
    description: "Create enterprise-grade integration with governance frameworks and institutional workflows",
    priority: "medium",
    owner: "Enterprise Team",
    estimatedCompletion: "Q2 2026",
    phases: [
      {
        id: "enterprise-security",
        title: "Enterprise Security & Compliance",
        description: "Implement enterprise-grade security with SOC2 compliance and data governance",
        status: "planned",
        startDate: "Sep 2025",
        endDate: "Nov 2025",
        deliverables: ["Security framework", "SOC2 compliance", "Data governance", "Access controls"],
        dependencies: ["API integration"],
      },
      {
        id: "workflow-integration",
        title: "Institutional Workflow Integration",
        description: "Integrate with institutional workflows including deal flow, risk management, and reporting",
        status: "planned",
        startDate: "Nov 2025",
        endDate: "Jan 2026",
        deliverables: ["Workflow integration", "Deal flow tracking", "Risk integration", "Custom reporting"],
        dependencies: ["Enterprise security"],
      },
      {
        id: "governance-framework",
        title: "ESG Governance Framework",
        description: "Build governance framework for ESG decision-making and stakeholder engagement",
        status: "planned",
        startDate: "Jan 2026",
        endDate: "Mar 2026",
        deliverables: ["Governance policies", "Stakeholder engagement", "Decision frameworks", "Oversight committees"],
        dependencies: ["Workflow integration"],
      },
    ],
  },
];