import { RoadmapItem } from "@/components/rve/roadmap-section";

// Marketplace Roadmap - Regenerative Trading Platform
export const MARKETPLACE_ROADMAP: RoadmapItem[] = [
  {
    id: "trading-engine",
    title: "High-Performance Trading Engine",
    description: "Build scalable order matching engine for RIU and ecological asset trading",
    priority: "critical",
    owner: "Trading Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "order-matching-core",
        title: "Core Order Matching Engine",
        description: "Implement high-performance order matching algorithms for RIU trading",
        status: "in-progress",
        progress: 30,
        startDate: "May 2025",
        endDate: "Jul 2025",
        deliverables: ["Matching engine", "Order book", "Trade execution"],
        dependencies: ["RIU minting"],
      },
      {
        id: "liquidity-pools",
        title: "Automated Market Making",
        description: "Implement AMM protocols for RIU liquidity and price discovery",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["AMM contracts", "Liquidity incentives", "Price oracles"],
        dependencies: ["Order matching core"],
      },
      {
        id: "cross-chain-settlement",
        title: "Cross-Chain Settlement",
        description: "Enable seamless trading across multiple blockchains and stablecoins",
        status: "planned",
        startDate: "Sep 2025",
        endDate: "Nov 2025",
        deliverables: ["Bridge integration", "Cross-chain settlement", "Asset wrapping"],
        dependencies: ["Liquidity pools"],
      },
    ],
  },
  {
    id: "impact-investing",
    title: "Impact Investment Platform",
    description: "Build platform for restoration funding, regenerative bonds, and impact-linked investments",
    priority: "high",
    owner: "Finance Team",
    estimatedCompletion: "Q1 2026",
    phases: [
      {
        id: "restoration-funding",
        title: "Restoration Project Funding",
        description: "Crowdfunding platform for verified ecological restoration projects",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["Project listings", "Funding rounds", "Milestone tracking"],
        dependencies: ["Oracle verification"],
      },
      {
        id: "regenerative-bonds",
        title: "Regenerative Bond Issuance",
        description: "Platform for issuing and trading bonds backed by restoration outcomes",
        status: "planned",
        startDate: "Oct 2025",
        endDate: "Dec 2025",
        deliverables: ["Bond issuance", "Secondary trading", "Coupon payments"],
        dependencies: ["Restoration funding"],
      },
      {
        id: "impact-linked-securities",
        title: "Impact-Linked Securities",
        description: "Complex financial instruments with payouts tied to ecological outcomes",
        status: "planned",
        startDate: "Dec 2025",
        endDate: "Feb 2026",
        deliverables: ["Derivative engine", "Impact oracles", "Structured products"],
        dependencies: ["Regenerative bonds"],
      },
    ],
  },
  {
    id: "ai-pricing",
    title: "AI-Powered Pricing & Risk Models",
    description: "Implement AI-driven pricing, risk assessment, and portfolio optimization",
    priority: "medium",
    owner: "Quant Team",
    estimatedCompletion: "Q2 2026",
    phases: [
      {
        id: "ecological-valuation",
        title: "Ecological Asset Valuation",
        description: "AI models for valuing ecological assets based on restoration impact",
        status: "planned",
        startDate: "Sep 2025",
        endDate: "Nov 2025",
        deliverables: ["Valuation models", "Impact pricing", "Scarcity algorithms"],
        dependencies: ["Data lake"],
      },
      {
        id: "risk-modeling",
        title: "Ecological Risk Modeling",
        description: "Build risk models for ecological and financial uncertainties",
        status: "planned",
        startDate: "Nov 2025",
        endDate: "Jan 2026",
        deliverables: ["Risk analytics", "Stress testing", "Portfolio optimization"],
        dependencies: ["Ecological valuation"],
      },
      {
        id: "predictive-analytics",
        title: "Predictive Market Analytics",
        description: "AI forecasting for market trends and ecological asset performance",
        status: "planned",
        startDate: "Jan 2026",
        endDate: "Mar 2026",
        deliverables: ["Market prediction", "Trend analysis", "Investment signals"],
        dependencies: ["Risk modeling"],
      },
    ],
  },
];