import { RoadmapItem } from "@/components/rve/roadmap-section";

// Nairobi Digital Twin Roadmap
export const NAIROBI_TWIN_ROADMAP: RoadmapItem[] = [
  {
    id: "digital-twin-core",
    title: "Digital Twin Core Infrastructure",
    description: "Build the foundational digital twin platform with 3D modeling and real-time data integration",
    priority: "critical",
    owner: "Twin Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "3d-modeling",
        title: "3D City Modeling",
        description: "Create detailed 3D models of Nairobi with buildings, infrastructure, and terrain",
        status: "in-progress",
        progress: 65,
        startDate: "Jan 2025",
        endDate: "Apr 2025",
        deliverables: ["3D city model", "Building data", "Infrastructure mapping", "Terrain modeling"],
        dependencies: ["GIS data acquisition"],
      },
      {
        id: "real-time-data",
        title: "Real-Time Data Integration",
        description: "Integrate real-time sensors for weather, air quality, traffic, and environmental data",
        status: "planned",
        startDate: "Apr 2025",
        endDate: "Jun 2025",
        deliverables: ["Sensor network", "Data pipelines", "Real-time APIs", "Data validation"],
        dependencies: ["3D modeling"],
      },
      {
        id: "simulation-engine",
        title: "Simulation Engine",
        description: "Build physics-based simulation engine for heat, flood, and air quality modeling",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Sep 2025",
        deliverables: ["Physics engine", "Simulation models", "Performance optimization", "Validation testing"],
        dependencies: ["Real-time data"],
      },
    ],
  },
  {
    id: "ecological-modeling",
    title: "Ecological & Climate Modeling",
    description: "Develop advanced ecological models for urban heat islands, flood risk, and green infrastructure",
    priority: "high",
    owner: "Ecology Team",
    estimatedCompletion: "Q1 2026",
    phases: [
      {
        id: "heat-island-model",
        title: "Urban Heat Island Modeling",
        description: "Create detailed heat island modeling with building materials, vegetation, and microclimate effects",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["Heat modeling", "Material properties", "Vegetation effects", "Microclimate analysis"],
        dependencies: ["Simulation engine"],
      },
      {
        id: "flood-risk-modeling",
        title: "Flood Risk & Water Modeling",
        description: "Build comprehensive flood risk modeling including river systems, drainage, and stormwater",
        status: "planned",
        startDate: "Sep 2025",
        endDate: "Nov 2025",
        deliverables: ["Flood modeling", "River systems", "Drainage analysis", "Stormwater modeling"],
        dependencies: ["Heat island model"],
      },
      {
        id: "green-infrastructure",
        title: "Green Infrastructure Planning",
        description: "Develop green infrastructure planning tools for tree cover, green roofs, and urban forests",
        status: "planned",
        startDate: "Nov 2025",
        endDate: "Jan 2026",
        deliverables: ["Tree planning", "Green roof modeling", "Urban forest analysis", "Biodiversity mapping"],
        dependencies: ["Flood risk modeling"],
      },
    ],
  },
  {
    id: "policy-simulation",
    title: "Policy Simulation & Decision Support",
    description: "Create policy simulation tools for urban planning, climate adaptation, and ecological restoration",
    priority: "medium",
    owner: "Policy Team",
    estimatedCompletion: "Q2 2026",
    phases: [
      {
        id: "scenario-modeling",
        title: "Scenario Modeling Platform",
        description: "Build scenario modeling platform for what-if analysis of policy interventions",
        status: "planned",
        startDate: "Oct 2025",
        endDate: "Dec 2025",
        deliverables: ["Scenario builder", "Policy templates", "Impact analysis", "Visualization tools"],
        dependencies: ["Ecological modeling"],
      },
      {
        id: "riu-integration",
        title: "RIU Integration & Incentives",
        description: "Integrate RIU incentives with policy simulation for ecological finance modeling",
        status: "planned",
        startDate: "Dec 2025",
        endDate: "Feb 2026",
        deliverables: ["RIU modeling", "Incentive analysis", "Finance integration", "Economic scenarios"],
        dependencies: ["Scenario modeling"],
      },
      {
        id: "stakeholder-interface",
        title: "Stakeholder Decision Interface",
        description: "Create user-friendly interface for stakeholders to explore scenarios and make decisions",
        status: "planned",
        startDate: "Feb 2026",
        endDate: "Apr 2026",
        deliverables: ["Stakeholder portal", "Decision tools", "Collaboration features", "Reporting dashboard"],
        dependencies: ["RIU integration"],
      },
    ],
  },
];