import { RoadmapItem } from "@/components/rve/roadmap-section";

// Oracle Roadmap - AI Verification Engine
export const ORACLE_ROADMAP: RoadmapItem[] = [
  {
    id: "multi-source-verification",
    title: "Multi-Source Verification Pipeline",
    description: "Build comprehensive verification system combining satellite, IoT, and community data sources",
    priority: "critical",
    owner: "Verification Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "data-ingestion",
        title: "Multi-Source Data Ingestion",
        description: "Build pipeline for ingesting data from satellites, sensors, and community reports",
        status: "in-progress",
        progress: 60,
        startDate: "Feb 2025",
        endDate: "Apr 2025",
        deliverables: ["Data ingestion pipeline", "Source validation", "Data normalization"],
        dependencies: ["IoT network", "Satellite integration"],
      },
      {
        id: "temporal-analysis",
        title: "Temporal Change Analysis",
        description: "AI-powered analysis of before/after ecological changes across time series",
        status: "planned",
        startDate: "Apr 2025",
        endDate: "Jun 2025",
        deliverables: ["Change detection algorithms", "Temporal analysis", "Confidence scoring"],
        dependencies: ["Data ingestion"],
      },
      {
        id: "consensus-engine",
        title: "Multi-Oracle Consensus Engine",
        description: "Build consensus system for combining multiple verification sources",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Aug 2025",
        deliverables: ["Consensus algorithms", "Weighting system", "Disagreement resolution"],
        dependencies: ["Temporal analysis"],
      },
    ],
  },
  {
    id: "fraud-detection",
    title: "Advanced Fraud Detection System",
    description: "AI-powered fraud detection for ecological claims and restoration verification",
    priority: "high",
    owner: "Security AI Team",
    estimatedCompletion: "Q1 2026",
    phases: [
      {
        id: "anomaly-detection",
        title: "Ecological Anomaly Detection",
        description: "Machine learning models for detecting anomalous ecological data and claims",
        status: "planned",
        startDate: "May 2025",
        endDate: "Jul 2025",
        deliverables: ["Anomaly models", "Pattern recognition", "Alert system"],
        dependencies: ["Data ingestion"],
      },
      {
        id: "image-forensics",
        title: "Image and Video Forensics",
        description: "AI analysis of uploaded images and videos for manipulation detection",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["Image analysis", "Video forensics", "Manipulation detection"],
        dependencies: ["Anomaly detection"],
      },
      {
        id: "behavioral-analysis",
        title: "Behavioral Pattern Analysis",
        description: "Analysis of user and community behavior patterns for fraud detection",
        status: "planned",
        startDate: "Sep 2025",
        endDate: "Nov 2025",
        deliverables: ["Behavioral models", "Pattern analysis", "Risk scoring"],
        dependencies: ["Image forensics"],
      },
    ],
  },
  {
    id: "audit-trail",
    title: "Immutable Audit Trail System",
    description: "Build tamper-evident audit trails for all verification decisions and data",
    priority: "high",
    owner: "Blockchain Team",
    estimatedCompletion: "Q3 2025",
    phases: [
      {
        id: "blockchain-integration",
        title: "Blockchain Audit Integration",
        description: "Integrate verification data with blockchain for immutable audit trails",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Aug 2025",
        deliverables: ["Blockchain integration", "Data anchoring", "Merkle trees"],
        dependencies: ["Smart contracts"],
      },
      {
        id: "tamper-detection",
        title: "Tamper Detection System",
        description: "Build system for detecting and alerting on data tampering attempts",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["Tamper detection", "Integrity monitoring", "Alert system"],
        dependencies: ["Blockchain integration"],
      },
      {
        id: "public-verification",
        title: "Public Verification Portal",
        description: "Public portal for verifying the integrity of audit trails and data",
        status: "planned",
        startDate: "Oct 2025",
        endDate: "Dec 2025",
        deliverables: ["Verification portal", "Public APIs", "Transparency tools"],
        dependencies: ["Tamper detection"],
      },
    ],
  },
];