import { RoadmapItem } from "@/components/rve/roadmap-section";

// Platform Architecture Roadmap - Implementation of all 20 pillars
export const PLATFORM_ROADMAP: RoadmapItem[] = [
  {
    id: "identity-layer",
    title: "Regenerative Identity Layer (RID)",
    description: "Establish trusted ecological participation with DID-based identities and reputation scoring",
    priority: "critical",
    owner: "Identity Team",
    estimatedCompletion: "Q2 2025",
    phases: [
      {
        id: "did-implementation",
        title: "DID Infrastructure Setup",
        description: "Implement decentralized identity protocols with wallet integration",
        status: "completed",
        progress: 100,
        startDate: "Jan 2025",
        endDate: "Feb 2025",
        deliverables: ["DID resolver", "Wallet integration", "VC issuance"],
        dependencies: ["Database schema"],
      },
      {
        id: "reputation-engine",
        title: "Reputation Scoring Engine",
        description: "Build RID scoring algorithm with ecological contribution tracking",
        status: "in-progress",
        progress: 75,
        startDate: "Feb 2025",
        endDate: "Apr 2025",
        deliverables: ["RID calculation", "Contribution tracking", "Score validation"],
        dependencies: ["DID infrastructure", "Oracle verification"],
      },
      {
        id: "anti-fraud",
        title: "Anti-Fraud Identity Validation",
        description: "Implement fraud detection and identity verification systems",
        status: "planned",
        startDate: "Apr 2025",
        endDate: "Jun 2025",
        deliverables: ["Fraud detection", "Identity validation", "Trust graphs"],
        risks: ["Regulatory compliance", "Privacy concerns"],
      },
    ],
  },
  {
    id: "oracle-engine",
    title: "AI Oracle Verification Engine",
    description: "Build the trust nucleus with multi-source ecological validation",
    priority: "critical",
    owner: "AI Team",
    estimatedCompletion: "Q3 2025",
    phases: [
      {
        id: "satellite-integration",
        title: "Satellite Imagery Integration",
        description: "Connect to satellite APIs for before/after ecological analysis",
        status: "in-progress",
        progress: 60,
        startDate: "Mar 2025",
        endDate: "May 2025",
        deliverables: ["Satellite API", "Image processing", "Change detection"],
        dependencies: ["Geospatial system"],
      },
      {
        id: "sensor-fusion",
        title: "IoT Sensor Fusion",
        description: "Integrate environmental sensors with edge AI validation",
        status: "planned",
        startDate: "May 2025",
        endDate: "Jul 2025",
        deliverables: ["Sensor network", "Edge AI", "Data fusion"],
        dependencies: ["IoT infrastructure"],
      },
      {
        id: "consensus-oracle",
        title: "Consensus Scoring System",
        description: "Build multi-oracle consensus for verification confidence",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["Consensus algorithm", "Confidence metrics", "Audit trails"],
        risks: ["Oracle reliability", "False positives"],
      },
    ],
  },
  {
    id: "riu-minting",
    title: "RIU Minting & Asset Engine",
    description: "Transform verified restoration into tradable ecological assets",
    priority: "high",
    owner: "Finance Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "asset-classification",
        title: "Asset Classification System",
        description: "Define and implement RIU asset classes (carbon, water, biodiversity, etc.)",
        status: "in-progress",
        progress: 40,
        startDate: "Apr 2025",
        endDate: "Jun 2025",
        deliverables: ["Asset taxonomy", "Classification engine", "Impact weighting"],
        dependencies: ["Oracle verification"],
      },
      {
        id: "minting-engine",
        title: "RIU Minting Engine",
        description: "Build automated RIU issuance based on verified ecological impact",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Aug 2025",
        deliverables: ["Minting contracts", "Issuance logic", "Supply controls"],
        dependencies: ["Smart contracts", "Asset classification"],
      },
      {
        id: "valuation-models",
        title: "Dynamic Valuation Models",
        description: "Implement AI-driven pricing and scarcity modeling",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["Pricing algorithms", "Market data", "Risk models"],
        risks: ["Market volatility", "Regulatory approval"],
      },
    ],
  },
  {
    id: "smart-contracts",
    title: "Smart Contract Infrastructure",
    description: "Build upgradeable, audited contracts for escrow, governance, and settlement",
    priority: "high",
    owner: "Blockchain Team",
    estimatedCompletion: "Q2 2025",
    phases: [
      {
        id: "modular-contracts",
        title: "Modular Contract Architecture",
        description: "Design upgradeable proxy patterns for all contract systems",
        status: "completed",
        progress: 100,
        startDate: "Dec 2024",
        endDate: "Feb 2025",
        deliverables: ["Proxy patterns", "Upgrade mechanisms", "Event indexing"],
      },
      {
        id: "escrow-system",
        title: "Escrow & Settlement System",
        description: "Implement automated escrow for marketplace and ReFi transactions",
        status: "in-progress",
        progress: 80,
        startDate: "Feb 2025",
        endDate: "Apr 2025",
        deliverables: ["Escrow contracts", "Settlement logic", "Dispute resolution"],
        dependencies: ["Modular contracts"],
      },
      {
        id: "governance-contracts",
        title: "Governance Execution Contracts",
        description: "Build contracts for proposal execution and treasury management",
        status: "planned",
        startDate: "Apr 2025",
        endDate: "Jun 2025",
        deliverables: ["Proposal execution", "Treasury controls", "Voting mechanisms"],
        dependencies: ["DAO governance"],
      },
    ],
  },
  {
    id: "geospatial-system",
    title: "Geospatial Intelligence System",
    description: "Create living maps of ecological systems with satellite and sensor data",
    priority: "high",
    owner: "Geospatial Team",
    estimatedCompletion: "Q3 2025",
    phases: [
      {
        id: "mapping-infrastructure",
        title: "Mapping Infrastructure Setup",
        description: "Implement PostGIS and mapping libraries for ecological visualization",
        status: "in-progress",
        progress: 70,
        startDate: "Jan 2025",
        endDate: "Mar 2025",
        deliverables: ["PostGIS setup", "Map rendering", "Data layers"],
      },
      {
        id: "ecological-heatmaps",
        title: "Ecological Heatmaps & Analytics",
        description: "Build heatmaps for restoration zones, biodiversity, and urban heat",
        status: "planned",
        startDate: "Mar 2025",
        endDate: "May 2025",
        deliverables: ["Heatmap generation", "Analytics dashboard", "Real-time updates"],
        dependencies: ["Mapping infrastructure"],
      },
      {
        id: "nairobi-twin-integration",
        title: "Digital Twin Integration",
        description: "Connect geospatial data to Nairobi digital twin simulation",
        status: "planned",
        startDate: "May 2025",
        endDate: "Jul 2025",
        deliverables: ["Twin data feeds", "Simulation inputs", "Scenario modeling"],
        dependencies: ["Digital twin engine"],
      },
    ],
  },
  {
    id: "iot-network",
    title: "IoT Environmental Sensor Network",
    description: "Deploy edge-validated environmental sensors across Nairobi",
    priority: "medium",
    owner: "IoT Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "sensor-hardware",
        title: "Sensor Hardware Deployment",
        description: "Deploy air, water, soil, and weather sensors across target areas",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Aug 2025",
        deliverables: ["Sensor procurement", "Installation", "Calibration"],
        risks: ["Hardware reliability", "Power constraints"],
      },
      {
        id: "edge-ai-validation",
        title: "Edge AI Validation",
        description: "Implement edge AI for real-time data validation before cloud upload",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["Edge models", "Validation logic", "Data filtering"],
        dependencies: ["Sensor hardware"],
      },
      {
        id: "network-infrastructure",
        title: "LPWAN Network Infrastructure",
        description: "Build low-power wide-area network for sensor connectivity",
        status: "planned",
        startDate: "Oct 2025",
        endDate: "Dec 2025",
        deliverables: ["Network setup", "MQTT brokers", "Data routing"],
        dependencies: ["Edge AI validation"],
      },
    ],
  },
  {
    id: "community-platform",
    title: "Community Steward Platform",
    description: "Build mobile-first platform for mass ecological participation",
    priority: "high",
    owner: "Community Team",
    estimatedCompletion: "Q3 2025",
    phases: [
      {
        id: "mobile-app",
        title: "Mobile App Development",
        description: "Build Flutter app for iOS/Android with offline capabilities",
        status: "in-progress",
        progress: 50,
        startDate: "Feb 2025",
        endDate: "May 2025",
        deliverables: ["Flutter app", "Offline sync", "Swahili/English UI"],
      },
      {
        id: "gamification-engine",
        title: "Gamification & Rewards Engine",
        description: "Implement mission system, leaderboards, and RIU rewards",
        status: "planned",
        startDate: "May 2025",
        endDate: "Jul 2025",
        deliverables: ["Mission system", "Reward logic", "Leaderboards"],
        dependencies: ["Mobile app", "RIU minting"],
      },
      {
        id: "mpesa-integration",
        title: "M-Pesa Payment Integration",
        description: "Connect community rewards to M-Pesa for instant payouts",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["Daraja integration", "Payout automation", "Settlement tracking"],
        dependencies: ["Gamification engine"],
      },
    ],
  },
  {
    id: "payment-infrastructure",
    title: "Mobile Wallet & Payment Infrastructure",
    description: "Build abstracted payment layer with M-Pesa and stablecoin support",
    priority: "high",
    owner: "Payments Team",
    estimatedCompletion: "Q2 2025",
    phases: [
      {
        id: "mpesa-rail",
        title: "M-Pesa Rail Implementation",
        description: "Complete Daraja API integration for STK push and B2C payments",
        status: "completed",
        progress: 100,
        startDate: "Nov 2024",
        endDate: "Jan 2025",
        deliverables: ["STK push", "B2C payouts", "Transaction tracking"],
      },
      {
        id: "stablecoin-wallet",
        title: "Stablecoin Wallet Integration",
        description: "Add USDC and other stablecoin support with account abstraction",
        status: "in-progress",
        progress: 60,
        startDate: "Jan 2025",
        endDate: "Mar 2025",
        deliverables: ["Wallet abstraction", "Stablecoin support", "Cross-chain bridging"],
        dependencies: ["M-Pesa rail"],
      },
      {
        id: "escrow-wallet",
        title: "Escrow & Custody System",
        description: "Build secure escrow wallets for marketplace transactions",
        status: "planned",
        startDate: "Mar 2025",
        endDate: "May 2025",
        deliverables: ["Escrow wallets", "Custody policies", "Multi-sig security"],
        dependencies: ["Stablecoin wallet"],
      },
    ],
  },
  {
    id: "digital-twin-engine",
    title: "Digital Twin Engine",
    description: "Create predictive simulation engine for Nairobi ecological-economic systems",
    priority: "medium",
    owner: "Simulation Team",
    estimatedCompletion: "Q1 2026",
    phases: [
      {
        id: "twin-architecture",
        title: "Twin Architecture Design",
        description: "Design modular twin architecture for ecological-economic simulation",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["Architecture design", "Data models", "Simulation framework"],
      },
      {
        id: "flood-modeling",
        title: "Flood Risk & Water System Modeling",
        description: "Build predictive models for flooding and water infrastructure",
        status: "planned",
        startDate: "Oct 2025",
        endDate: "Dec 2025",
        deliverables: ["Flood models", "Water simulation", "Risk assessment"],
        dependencies: ["Twin architecture"],
      },
      {
        id: "policy-simulation",
        title: "Policy Impact Simulation",
        description: "Enable what-if scenarios for ecological and urban policies",
        status: "planned",
        startDate: "Dec 2025",
        endDate: "Feb 2026",
        deliverables: ["Policy simulator", "Scenario analysis", "Impact forecasting"],
        dependencies: ["Flood modeling"],
      },
    ],
  },
  {
    id: "marketplace-engine",
    title: "Regenerative Marketplace",
    description: "Build liquidity layer for RIUs, impact investing, and ecological derivatives",
    priority: "high",
    owner: "Trading Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "order-matching",
        title: "Order Matching Engine",
        description: "Implement high-performance order matching for RIU trading",
        status: "in-progress",
        progress: 30,
        startDate: "May 2025",
        endDate: "Jul 2025",
        deliverables: ["Matching engine", "Order book", "Trade execution"],
        dependencies: ["RIU minting"],
      },
      {
        id: "impact-investing",
        title: "Impact Investment Platform",
        description: "Build platform for restoration funding and regenerative bonds",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["Investment dashboard", "Bond issuance", "Impact tracking"],
        dependencies: ["Order matching"],
      },
      {
        id: "ai-pricing",
        title: "AI Pricing & Derivatives",
        description: "Implement AI-driven pricing models and ecological derivatives",
        status: "planned",
        startDate: "Sep 2025",
        endDate: "Nov 2025",
        deliverables: ["Pricing models", "Derivatives engine", "Risk analytics"],
        dependencies: ["Impact investing"],
      },
    ],
  },
];