import { RoadmapItem } from "@/components/rve/roadmap-section";

// Regenerative Finance (ReFi) Roadmap
export const REFI_ROADMAP: RoadmapItem[] = [
  {
    id: "defi-infrastructure",
    title: "DeFi Infrastructure & Smart Contracts",
    description: "Build the core DeFi infrastructure with smart contracts for lending, staking, and liquidity pools",
    priority: "critical",
    owner: "DeFi Team",
    estimatedCompletion: "Q4 2025",
    phases: [
      {
        id: "smart-contracts",
        title: "Core Smart Contracts",
        description: "Develop audited smart contracts for RIU tokens, lending protocols, and yield farming",
        status: "in-progress",
        progress: 70,
        startDate: "Mar 2025",
        endDate: "Jun 2025",
        deliverables: ["RIU token contract", "Lending protocol", "Yield farming", "Security audit"],
        dependencies: ["Blockchain setup"],
      },
      {
        id: "liquidity-pools",
        title: "Liquidity Pool System",
        description: "Implement automated market maker (AMM) pools for RIU and ecological asset trading",
        status: "planned",
        startDate: "Jun 2025",
        endDate: "Aug 2025",
        deliverables: ["AMM contracts", "Pool management", "Fee collection", "Liquidity incentives"],
        dependencies: ["Smart contracts"],
      },
      {
        id: "yield-mechanisms",
        title: "Yield Generation Mechanisms",
        description: "Build yield farming, staking, and reward distribution systems tied to ecological outcomes",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["Staking contracts", "Reward distribution", "Yield optimization", "Risk management"],
        dependencies: ["Liquidity pools"],
      },
    ],
  },
  {
    id: "impact-lending",
    title: "Impact Lending & Collateral System",
    description: "Develop impact-focused lending protocols with ecological collateral and risk assessment",
    priority: "high",
    owner: "Lending Team",
    estimatedCompletion: "Q1 2026",
    phases: [
      {
        id: "ecological-collateral",
        title: "Ecological Collateral Framework",
        description: "Create collateral system backed by verified ecological assets and restoration projects",
        status: "planned",
        startDate: "Jul 2025",
        endDate: "Sep 2025",
        deliverables: ["Collateral valuation", "Asset tokenization", "Risk assessment", "Liquidation protocols"],
        dependencies: ["Smart contracts"],
      },
      {
        id: "impact-loans",
        title: "Impact-Linked Loans",
        description: "Implement loans with terms tied to ecological outcomes and restoration milestones",
        status: "planned",
        startDate: "Sep 2025",
        endDate: "Nov 2025",
        deliverables: ["Loan contracts", "Impact tracking", "Milestone verification", "Dynamic terms"],
        dependencies: ["Ecological collateral"],
      },
      {
        id: "credit-scoring",
        title: "Ecological Credit Scoring",
        description: "Build credit scoring system based on RID scores and ecological impact history",
        status: "planned",
        startDate: "Nov 2025",
        endDate: "Jan 2026",
        deliverables: ["Credit algorithms", "Score calculation", "Borrower profiles", "Risk modeling"],
        dependencies: ["Impact loans"],
      },
    ],
  },
  {
    id: "mobile-defi",
    title: "Mobile-First DeFi Experience",
    description: "Create mobile-optimized DeFi interface with M-Pesa integration and simplified user experience",
    priority: "medium",
    owner: "Mobile Team",
    estimatedCompletion: "Q2 2026",
    phases: [
      {
        id: "mobile-wallet",
        title: "Mobile Wallet Integration",
        description: "Build mobile wallet with support for RIU tokens, staking, and DeFi interactions",
        status: "planned",
        startDate: "Aug 2025",
        endDate: "Oct 2025",
        deliverables: ["Wallet interface", "Token management", "Transaction signing", "Security features"],
        dependencies: ["Smart contracts"],
      },
      {
        id: "mpesa-defi",
        title: "M-Pesa DeFi Integration",
        description: "Integrate M-Pesa for seamless fiat on/off-ramps and DeFi settlement",
        status: "planned",
        startDate: "Oct 2025",
        endDate: "Dec 2025",
        deliverables: ["Fiat on-ramps", "Settlement rails", "Payment flows", "Compliance"],
        dependencies: ["Mobile wallet"],
      },
      {
        id: "simplified-ui",
        title: "Simplified DeFi UX",
        description: "Create simplified user interface for complex DeFi operations with guided workflows",
        status: "planned",
        startDate: "Dec 2025",
        endDate: "Feb 2026",
        deliverables: ["Guided workflows", "Simplified UI", "Educational content", "Risk warnings"],
        dependencies: ["M-Pesa DeFi"],
      },
    ],
  },
];